run:
  timeout: 10m
  go: "1.23"

linters:
  enable:
    - govet
    - errcheck

linters-settings:
  errcheck:
    exclude-functions:
      - (*log.Logger).Printf
      - fmt.Printf

issues:
  max-issues-per-linter: 50
  max-same-issues: 10