# golangci-lint configuration version
version: 2

run:
  timeout: 10m
  go: "1.23"

linters:
  enable:
    - govet
    - errcheck
    - gosec
    - staticcheck
    - unused
    - ineffassign
    - misspell

linters-settings:
  govet:
    check-shadowing: false
    settings:
      composites:
        enabled: false

issues:
  # Focus on new issues - this is professional software development practice
  new-from-patch: true
  exclude-use-default: true
