run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec

linters-settings:
  gosec:
    excludes:
      - G101 # Look for hardcoded credentials
      - G104 # Errors unhandled
      - G204 # Audit use of command execution
      - G304 # File path provided as taint input
      - G404 # Use of weak random number generator
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: internal/llm/
      linters:
        - gosec
    - path: pkg/auth/
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0