package version

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

type wailsConfig struct {
	Info struct {
		ProductVersion string `json:"productVersion"`
	} `json:"info"`
}

type packageJSON struct {
	Version string `json:"version"`
}

func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("get working directory: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("repository root containing go.mod not found")
		}
		dir = parent
	}
}

// TestVersionMatchesVersionFile guards against the classic release miss: bumping
// one place but not the other. The VERSION file (read by Makefile/CI) and the
// compiled-in version.Version must always agree on main.
func TestVersionMatchesVersionFile(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "VERSION")) // #nosec G304 -- fixed repo file resolved from runtime.Caller
	if err != nil {
		t.Fatalf("read VERSION: %v", err)
	}
	fileVer := strings.TrimSuffix(string(raw), "\n")
	if fileVer != Version {
		t.Fatalf("VERSION file = %q but version.Version = %q — bump both together (see docs/RELEASE_PROCEDURE.md)", fileVer, Version)
	}
}

// TestChangelogHasCurrentVersion ensures the release notes were updated for the
// version being shipped. Looks for a "## [X.Y.Z]" heading (Keep a Changelog style).
func TestChangelogHasCurrentVersion(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "CHANGELOG.md")) // #nosec G304 -- fixed repo file resolved from runtime.Caller
	if err != nil {
		t.Fatalf("read CHANGELOG.md: %v", err)
	}
	// Match "## [1.24.0]" allowing surrounding whitespace.
	re := regexp.MustCompile(`(?m)^##[\t ]+\[` + regexp.QuoteMeta(Version) + `\]([\t ]|$)`)
	if !re.Match(raw) {
		t.Fatalf("CHANGELOG.md has no '## [%s]' entry — add the release notes before tagging (see docs/RELEASE_PROCEDURE.md)", Version)
	}
}

// TestHomebrewCaskTemplateVersion keeps the in-repo Homebrew cask template in sync
// with the release version. The user-facing tap cask is regenerated by CI, but this
// source-of-truth template silently drifted for several releases; pinning it here
// makes the drift a CI failure instead of a post-release surprise.
func TestHomebrewCaskTemplateVersion(t *testing.T) {
	root := repoRoot(t)
	path := filepath.Join(root, "packaging", "homebrew", "giztui-desktop.rb")
	raw, err := os.ReadFile(path) // #nosec G304 -- fixed repo file resolved from runtime.Caller
	if err != nil {
		t.Fatalf("read cask template: %v", err)
	}
	re := regexp.MustCompile(`(?m)^\s*version\s+"([^"]+)"`)
	m := re.FindSubmatch(raw)
	if m == nil {
		t.Fatalf("cask template %s has no version stanza", path)
	}
	if got := string(m[1]); got != Version {
		t.Fatalf("cask template version = %q but version.Version = %q — bump packaging/homebrew/giztui-desktop.rb too (see docs/RELEASE_PROCEDURE.md)", got, Version)
	}
}

func TestDesktopProductVersion(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "desktop", "wails.json")) // #nosec G304 -- fixed repo file resolved from runtime.Caller
	if err != nil {
		t.Fatalf("read desktop/wails.json: %v", err)
	}
	var config wailsConfig
	if err := json.Unmarshal(raw, &config); err != nil {
		t.Fatalf("parse desktop/wails.json: %v", err)
	}
	versionCore := strings.SplitN(strings.SplitN(Version, "+", 2)[0], "-", 2)[0]
	if config.Info.ProductVersion != versionCore {
		t.Fatalf("desktop productVersion = %q but release version core = %q", config.Info.ProductVersion, versionCore)
	}
}

func TestDesktopFrontendVersion(t *testing.T) {
	root := repoRoot(t)
	for _, name := range []string{"package.json", "package-lock.json"} {
		raw, err := os.ReadFile(filepath.Join(root, "desktop", "frontend", name)) // #nosec G304 -- fixed repo file resolved from repository root
		if err != nil {
			t.Fatalf("read desktop/frontend/%s: %v", name, err)
		}
		var manifest packageJSON
		if err := json.Unmarshal(raw, &manifest); err != nil {
			t.Fatalf("parse desktop/frontend/%s: %v", name, err)
		}
		if manifest.Version != Version {
			t.Fatalf("desktop/frontend/%s version = %q but version.Version = %q", name, manifest.Version, Version)
		}
	}
}
