package version

import (
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"
)

// repoRoot returns the repository root relative to this test file
// (internal/version/consistency_test.go → ../../).
func repoRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", ".."))
}

// TestVersionMatchesVersionFile guards against the classic release miss: bumping
// one place but not the other. The VERSION file (read by Makefile/CI) and the
// compiled-in version.Version must always agree on main.
func TestVersionMatchesVersionFile(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "VERSION")) // #nosec G304 -- fixed repo file resolved from runtime.Caller
	if err != nil {
		t.Fatalf("read VERSION: %v", err)
	}
	fileVer := strings.TrimSpace(string(raw))
	if fileVer != Version {
		t.Fatalf("VERSION file = %q but version.Version = %q — bump both together (see docs/RELEASE_PROCEDURE.md)", fileVer, Version)
	}
}

// TestChangelogHasCurrentVersion ensures the release notes were updated for the
// version being shipped. Looks for a "## [X.Y.Z]" heading (Keep a Changelog style).
func TestChangelogHasCurrentVersion(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "CHANGELOG.md")) // #nosec G304 -- fixed repo file resolved from runtime.Caller
	if err != nil {
		t.Fatalf("read CHANGELOG.md: %v", err)
	}
	// Match "## [1.24.0]" allowing surrounding whitespace.
	re := regexp.MustCompile(`(?m)^##\s*\[` + regexp.QuoteMeta(Version) + `\]`)
	if !re.Match(raw) {
		t.Fatalf("CHANGELOG.md has no '## [%s]' entry — add the release notes before tagging (see docs/RELEASE_PROCEDURE.md)", Version)
	}
}

// TestHomebrewCaskTemplateVersion keeps the in-repo Homebrew cask template in sync
// with the release version. The user-facing tap cask is regenerated by CI, but this
// source-of-truth template silently drifted for several releases; pinning it here
// makes the drift a CI failure instead of a post-release surprise.
func TestHomebrewCaskTemplateVersion(t *testing.T) {
	root := repoRoot(t)
	path := filepath.Join(root, "packaging", "homebrew", "giztui-desktop.rb")
	raw, err := os.ReadFile(path) // #nosec G304 -- fixed repo file resolved from runtime.Caller
	if err != nil {
		t.Fatalf("read cask template: %v", err)
	}
	re := regexp.MustCompile(`(?m)^\s*version\s+"([^"]+)"`)
	m := re.FindSubmatch(raw)
	if m == nil {
		t.Fatalf("cask template %s has no version stanza", path)
	}
	if got := string(m[1]); got != Version {
		t.Fatalf("cask template version = %q but version.Version = %q — bump packaging/homebrew/giztui-desktop.rb too (see docs/RELEASE_PROCEDURE.md)", got, Version)
	}
}
