package tui

// This file generates docs/COMMANDS.md from the live command table and
// config.DefaultConfig(), so the reference can never drift from the code.
//
//   make gen-command-ref            # write docs/COMMANDS.md
//   go test ./internal/tui -run CommandReference   # verify it is current
//
// The verification test always runs as part of the canonical Go gate
// (go test ./internal/...): docs/COMMANDS.md must match the generated output.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"

	"github.com/ajramos/giztui/internal/config"
)

func repoRootFromTest(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("repository root not found")
		}
		dir = parent
	}
}

func handlerName(fn func([]string)) string {
	return runtime.FuncForPC(reflect.ValueOf(fn).Pointer()).Name()
}

func buildCommandReference() string {
	a := &App{}
	table := a.commandTable()

	groups := map[string][]string{}
	for token, fn := range table {
		name := handlerName(fn)
		name = strings.TrimSuffix(name, "-fm")
		if i := strings.LastIndex(name, "."); i >= 0 {
			name = name[i+1:]
		}
		groups[name] = append(groups[name], token)
	}

	handlers := make([]string, 0, len(groups))
	for h := range groups {
		handlers = append(handlers, h)
	}
	sort.Strings(handlers)
	for h := range groups {
		sort.Strings(groups[h])
	}

	cfgJSON, err := json.MarshalIndent(config.DefaultConfig(), "  ", "  ")
	if err != nil {
		cfgJSON = []byte("(unmarshalable default config: " + err.Error() + ")")
	}

	var b strings.Builder
	b.WriteString("<!-- Generated by internal/tui/command_ref_test.go (make gen-command-ref). DO NOT EDIT. -->\n")
	b.WriteString("# Command Reference\n\n")
	b.WriteString("This file is generated from the live `commandTable()` in " +
		"`internal/tui/commands.go` and `config.DefaultConfig()`. The canonical Go " +
		"gate fails if this file is out of date.\n\n")
	b.WriteString("Every token is a `:command` name or alias; aliases sharing a " +
		"handler are grouped together.\n\n")
	for _, h := range handlers {
		b.WriteString("## " + h + "\n\n")
		b.WriteString("```text\n:" + strings.Join(groups[h], " :") + "\n```\n\n")
	}
	b.WriteString("## Default Configuration\n\n")
	b.WriteString("The canonical default `~/.config/giztui/config.json`, as produced " +
		"by `config.DefaultConfig()`:\n\n")
	b.WriteString("```json\n" + string(cfgJSON) + "\n```\n")
	return b.String()
}

func writeCommandReference(t *testing.T, content string) string {
	t.Helper()
	root := repoRootFromTest(t)
	path := filepath.Join(root, "docs", "COMMANDS.md")
	// #nosec G306 -- generated docs file; public read is intended
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
	return path
}

func TestCommandReferenceGeneration(t *testing.T) {
	content := buildCommandReference()
	if os.Getenv("UPDATE_COMMAND_REF") == "true" {
		writeCommandReference(t, content)
	}
	root := repoRootFromTest(t)
	path := filepath.Join(root, "docs", "COMMANDS.md")
	raw, err := os.ReadFile(path) // #nosec G304 -- fixed repo docs file resolved from repository root
	if err != nil {
		t.Fatalf("read %s: %v — run 'make gen-command-ref' to generate it", path, err)
	}
	if string(raw) != content {
		t.Fatalf("%s is out of date with the command table / DefaultConfig — "+
			"run 'make gen-command-ref' and commit the change", path)
	}
}
