// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/ajramos/giztui/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// DeterministicRulesService is an autogenerated mock type for the DeterministicRulesService type
type DeterministicRulesService struct {
	mock.Mock
}

// DeleteRule provides a mock function with given fields: ctx, id
func (_m *DeterministicRulesService) DeleteRule(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListRules provides a mock function with given fields: ctx
func (_m *DeterministicRulesService) ListRules(ctx context.Context) ([]services.DeterministicRuleInfo, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRules")
	}

	var r0 []services.DeterministicRuleInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]services.DeterministicRuleInfo, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []services.DeterministicRuleInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.DeterministicRuleInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Partition provides a mock function with given fields: ctx, scopeQuery, candidates
func (_m *DeterministicRulesService) Partition(ctx context.Context, scopeQuery string, candidates []string) ([]services.RuleMatch, []string, error) {
	ret := _m.Called(ctx, scopeQuery, candidates)

	if len(ret) == 0 {
		panic("no return value specified for Partition")
	}

	var r0 []services.RuleMatch
	var r1 []string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) ([]services.RuleMatch, []string, error)); ok {
		return rf(ctx, scopeQuery, candidates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) []services.RuleMatch); ok {
		r0 = rf(ctx, scopeQuery, candidates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.RuleMatch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) []string); ok {
		r1 = rf(ctx, scopeQuery, candidates)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []string) error); ok {
		r2 = rf(ctx, scopeQuery, candidates)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SaveRule provides a mock function with given fields: ctx, query, action, label, promptID
func (_m *DeterministicRulesService) SaveRule(ctx context.Context, query string, action string, label string, promptID int64) (*services.DeterministicRuleInfo, error) {
	ret := _m.Called(ctx, query, action, label, promptID)

	if len(ret) == 0 {
		panic("no return value specified for SaveRule")
	}

	var r0 *services.DeterministicRuleInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) (*services.DeterministicRuleInfo, error)); ok {
		return rf(ctx, query, action, label, promptID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) *services.DeterministicRuleInfo); ok {
		r0 = rf(ctx, query, action, label, promptID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.DeterministicRuleInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64) error); ok {
		r1 = rf(ctx, query, action, label, promptID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetAccountEmail provides a mock function with given fields: email
func (_m *DeterministicRulesService) SetAccountEmail(email string) {
	_m.Called(email)
}

// SyncRule provides a mock function with given fields: ctx, id
func (_m *DeterministicRulesService) SyncRule(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SyncRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnsyncRule provides a mock function with given fields: ctx, id
func (_m *DeterministicRulesService) UnsyncRule(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UnsyncRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateRule provides a mock function with given fields: ctx, id, query, action, label, promptID
func (_m *DeterministicRulesService) UpdateRule(ctx context.Context, id int64, query string, action string, label string, promptID int64) error {
	ret := _m.Called(ctx, id, query, action, label, promptID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string, string, int64) error); ok {
		r0 = rf(ctx, id, query, action, label, promptID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeterministicRulesService creates a new instance of DeterministicRulesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeterministicRulesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeterministicRulesService {
	mock := &DeterministicRulesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
