// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/ajramos/giztui/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// PromptGeneratorService is an autogenerated mock type for the PromptGeneratorService type
type PromptGeneratorService struct {
	mock.Mock
}

// GenerateFromIntent provides a mock function with given fields: ctx, intent, opts
func (_m *PromptGeneratorService) GenerateFromIntent(ctx context.Context, intent string, opts services.PromptGenerationOptions) (*services.GeneratedPrompt, error) {
	ret := _m.Called(ctx, intent, opts)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromIntent")
	}

	var r0 *services.GeneratedPrompt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.PromptGenerationOptions) (*services.GeneratedPrompt, error)); ok {
		return rf(ctx, intent, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.PromptGenerationOptions) *services.GeneratedPrompt); ok {
		r0 = rf(ctx, intent, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.GeneratedPrompt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.PromptGenerationOptions) error); ok {
		r1 = rf(ctx, intent, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateFromIntentStream provides a mock function with given fields: ctx, intent, opts, onToken
func (_m *PromptGeneratorService) GenerateFromIntentStream(ctx context.Context, intent string, opts services.PromptGenerationOptions, onToken func(string)) (*services.GeneratedPrompt, error) {
	ret := _m.Called(ctx, intent, opts, onToken)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromIntentStream")
	}

	var r0 *services.GeneratedPrompt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.PromptGenerationOptions, func(string)) (*services.GeneratedPrompt, error)); ok {
		return rf(ctx, intent, opts, onToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.PromptGenerationOptions, func(string)) *services.GeneratedPrompt); ok {
		r0 = rf(ctx, intent, opts, onToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.GeneratedPrompt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.PromptGenerationOptions, func(string)) error); ok {
		r1 = rf(ctx, intent, opts, onToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefinePrompt provides a mock function with given fields: ctx, currentPrompt, refinement, opts
func (_m *PromptGeneratorService) RefinePrompt(ctx context.Context, currentPrompt string, refinement string, opts services.PromptGenerationOptions) (*services.GeneratedPrompt, error) {
	ret := _m.Called(ctx, currentPrompt, refinement, opts)

	if len(ret) == 0 {
		panic("no return value specified for RefinePrompt")
	}

	var r0 *services.GeneratedPrompt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.PromptGenerationOptions) (*services.GeneratedPrompt, error)); ok {
		return rf(ctx, currentPrompt, refinement, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.PromptGenerationOptions) *services.GeneratedPrompt); ok {
		r0 = rf(ctx, currentPrompt, refinement, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.GeneratedPrompt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.PromptGenerationOptions) error); ok {
		r1 = rf(ctx, currentPrompt, refinement, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefinePromptStream provides a mock function with given fields: ctx, currentPrompt, refinement, opts, onToken
func (_m *PromptGeneratorService) RefinePromptStream(ctx context.Context, currentPrompt string, refinement string, opts services.PromptGenerationOptions, onToken func(string)) (*services.GeneratedPrompt, error) {
	ret := _m.Called(ctx, currentPrompt, refinement, opts, onToken)

	if len(ret) == 0 {
		panic("no return value specified for RefinePromptStream")
	}

	var r0 *services.GeneratedPrompt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.PromptGenerationOptions, func(string)) (*services.GeneratedPrompt, error)); ok {
		return rf(ctx, currentPrompt, refinement, opts, onToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.PromptGenerationOptions, func(string)) *services.GeneratedPrompt); ok {
		r0 = rf(ctx, currentPrompt, refinement, opts, onToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.GeneratedPrompt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.PromptGenerationOptions, func(string)) error); ok {
		r1 = rf(ctx, currentPrompt, refinement, opts, onToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPromptGeneratorService creates a new instance of PromptGeneratorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPromptGeneratorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PromptGeneratorService {
	mock := &PromptGeneratorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
